import { ethers } from 'ethers';
import { create as ipfsHttpClient } from 'ipfs-http-client';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Web3Modal from 'web3modal';
import Alexa4Musicians_721 from '/home/mvnu/projects/erc721_upgradable_smart_contract/artifacts/contracts/Alexa4Musicians_721.sol/Alexa4Musicians_721.json';
import { useEffect, useState } from 'react';
import React from 'react';
import Button from '@material-tailwind/react/Button';
const client = ipfsHttpClient('https://ipfs.infura.io:5001/api/v0');
export default function Home() {
  const [provider, setProvider] = useState();
  const [web3Modal, setWeb3Modal] = useState();
  const [library, setLibrary] = useState();
  const [account, setAccount] = useState();
  const [error, setError] = useState('');
  const [chainId, setChainId] = useState();
  const [network, setNetwork] = useState();
  const connectWallet = async () => {
    try {
      const web3Modal = new Web3Modal();
      setWeb3Modal(web3Modal);
      const provider = await web3Modal.connect();
      const library = new ethers.providers.Web3Provider(provider);
      const accounts = await library.listAccounts();
      const network = await library.getNetwork();
      setProvider(provider);
      setLibrary(library);
      setAccount(accounts[0]);
      if (accounts) {
        setChainId(network.chainId);
      }
    } catch (error) {
      setError(error);
    }
  };

  const handleNetwork = (e) => {
    const id = e.target.value;
    setNetwork(Number(id));
  };
  const refreshState = () => {
    setAccount();
    setChainId();
    setNetwork('');
  };
  useEffect(() => {
    if (web3Modal) {
      connectWallet();
    }
  }, []);
  const disconnect = async () => {
    await web3Modal.clearCachedProvider();
    refreshState();
  };
  const contract_init = async () => {
    const web3Modal = new Web3Modal();
    const connection = await web3Modal.connect();
    const provider = new ethers.providers.Web3Provider(connection);
    const signer = provider.getSigner();
    const contract = new ethers.Contract(
      '0x812770C422D66476659cd2D0F2E0BC46ee68c0cc',
      Alexa4Musicians_721.abi,
      signer
    );
    return contract;
  };
  const mint = async (e) => {
    e.preventDefault();
    try {
      const contract = await contract_init();
      const url = `https://gateway.pinata.cloud/ipfs/QmchHMxjZETrzTXFwVVPh2tE9n1y2wRfLdjLCNeJj33jnb`;
      // let setFee = await contract.setMintingFee(5);
      //  let t = await setFee.wait();
      let fee = await contract.getMaticFee(true);
      console.log(fee.toString());
      const data = JSON.stringify({
        name: 'sameer_alexa_skill',
        description: 'alexa skill created by sameer',
        image: url,
        attributes: [{ trait_type: 'Skill_Id', value: 'ask1392084098235' }]
      });
      const added = await client.add(data);
      const ipfsURL = `https://ipfs.infura.io/ipfs/${added.path}`;
      let trans = await contract.mint(ipfsURL, 'ask1392084098235', true, {
        gasPrice: ethers.utils.parseUnits('30', 'gwei'),
        gasLimit: 1000000,
        value: fee.toString()
      });

      let tx = await trans.wait();
    } catch (err) {
      console.error(err);
      alert(err.data.message);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Material Icons Link */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        {/* Font Awesome Link */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
          integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {!account ? (
          <Button color="blueGray" ripple="light" onClick={connectWallet}>
            Connect Wallet
          </Button>
        ) : (
          <Button color="lightBlue" ripple="light" onClick={mint}>
            Mint
          </Button>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
