import { ethers } from 'ethers';
import { create as ipfsHttpClient } from 'ipfs-http-client';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Web3Modal from 'web3modal';
import Alexa4Musicians_721 from '/home/mvnu/Desktop/projects/erc721_upgradable_smart_contract/artifacts/contracts/Alexa4Musicians_721.sol/Alexa4Musicians_721.json';
import { useEffect } from 'react';
import React from 'react';
import Button from '@material-tailwind/react/Button';
const client = ipfsHttpClient('https://ipfs.infura.io:5001/api/v0');
export default function Home() {
  const contract_init = async () => {
    const web3Modal = new Web3Modal();
    const connection = await web3Modal.connect();
    const provider = new ethers.providers.Web3Provider(connection);
    const signer = provider.getSigner();
    const contract = new ethers.Contract(
      '0x812770C422D66476659cd2D0F2E0BC46ee68c0cc',
      Alexa4Musicians_721.abi,
      signer
    );
    return contract;
  };
  const mint = async (e) => {
    e.preventDefault();
    const contract = await contract_init();
    const url = `https://gateway.pinata.cloud/ipfs/QmchHMxjZETrzTXFwVVPh2tE9n1y2wRfLdjLCNeJj33jnb`;
    // let setFee = await contract.setMintingFee(5);
    //  let t = await setFee.wait();
    let fee = await contract.getMaticFee(true);
    console.log(fee.toString());
    const data = JSON.stringify({
      name: 'sameer_alexa_skill',
      description: 'alexa skill created by sameer',
      image: url,
      attributes: [{ trait_type: 'Skill_Id', value: 'ask1392084098234' }]
    });
    const added = await client.add(data);
    const ipfsURL = `https://ipfs.infura.io/ipfs/${added.path}`;
    let trans = await contract.mint(ipfsURL, true, { value: fee.toString() });
    let tx = await trans.wait();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Material Icons Link */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        {/* Font Awesome Link */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
          integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Button color="lightBlue" ripple="light" onClick={mint}>
          Mint
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
