import { ethers } from 'ethers';
import { create as ipfsHttpClient } from 'ipfs-http-client';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Web3Modal from 'web3modal';
import Alexa4Musicians_721 from '/home/sam/Desktop/projects/mvnu/capstone/artifacts/contracts/Alexa4Musicians_721.sol/Alexa4Musicians_721.json';
import { useEffect } from 'react';
const client = ipfsHttpClient('https://ipfs.infura.io:5001/api/v0');
export default function Home() {
  const mint = async () => {
    const web3Modal = new Web3Modal();
    const connection = await web3Modal.connect();
    const provider = new ethers.providers.Web3Provider(connection);
    const signer = provider.getSigner();
    const contract = new ethers.Contract(
      '0x1EedF9167c0a6f439b6696AbBf0d48434eCBb6F9',
      Alexa4Musicians_721.abi,
      signer
    );
    const url = `https://gateway.pinata.cloud/ipfs/QmchHMxjZETrzTXFwVVPh2tE9n1y2wRfLdjLCNeJj33jnb`;
    // let setFee = await contract.setMintingFee(5);
    // let t = await setFee.wait();
    let fee = await contract.getMintingFee();
    let balance = await contract.getBalance()
    let owner = await contract.getOwnerAddress()
    console.log(owner.toString());
    const data = JSON.stringify({
      name: 'sameer_alexa_skill',
      description: 'alexa skill created by sameer',
      image: url,
      attributes: [{ trait_type: 'Skill_Id', value: 'ask1392084098234' }]
    });
    const added = await client.add(data);
    const ipfsURL = `https://ipfs.infura.io/ipfs/${added.path}`;
    let trans = await contract.mint(ipfsURL, { value: fee.toString() });
    let tx = await trans.wait();
  };
  useEffect(() => {
    (async () => {
      await mint();
    })();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
